### ISSUE TITLE
[Feature Request]: Support for non-latin characters

### ISSUE THREAD

**Issue by piotrekwitkowski** [cloudscape-design/global-styles#22]
### Description

When I tried to use some Polish letters inside a `<Box />` and a `<Button />` for a `noMatch` prop in one of the components, I've noticed that some of them (for example **ć** and **ś**) were rendered incorrectly. Cloudscape provides [just the latin version](https://github.com/cloudscape-design/global-styles/blob/main/src/index.css) of the Open Sans font, and characters from latin-ext are missing.

How Cloudscape renders Polish letters:
<img width="615" alt="image" src="https://user-images.githubusercontent.com/17732966/205021191-99b9e153-3e2b-48dc-b56b-b3f4aec1d8b1.png">

How they should be rendered:
<img width="615" alt="image" src="https://user-images.githubusercontent.com/17732966/205021230-bf63ff87-4dbc-4e30-8ceb-93fd1ff53c76.png">

I would appreciate the built-in support for the missing font versions, but also understand that it's not how the package is commonly used. However, ability to opt-in to support other character sets or at least see more documentation on how to overcome this limitation would be a great addition to the system.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/cloudscape-design/global-styles/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/cloudscape-design/global-styles/issues) for duplicate requests

**Comment by johannes-weber** [comment]
Hi @piotrekwitkowski, we're using this feature request to track the interest about extending the character support.

To unblock you, you could make use of [incremental font transfer](https://www.w3.org/TR/IFT/) by - additionally - loading your own font files contributing different character sets for Open Sans.

Here's a reference where you can generate your own version of Open Sance containing a specific charset: https://github.com/cloudscape-design/global-styles/blob/main/src/fonts/README.md

**Comment by piotrekwitkowski** [comment]
Hi Johannes, I solved it then (faster?) by installing [@fontsource/open-sans](https://www.npmjs.com/package/@fontsource/open-sans) from npm and adding 
```
import "@fontsource/open-sans/latin-ext.css";
```
to my React app. Please feel free to reopen if needed.
